Simulacion de cola de espera de K servidores

In [20]:
import numpy as np
import pandas as pd
import datetime

funciones auxiliares

In [21]:
def acumular_array(array):
    acumulado = 0
    array_acumulado = []
    for n in array :
        acumulado = n + acumulado
        array_acumulado.append(acumulado)
    return array_acumulado

1.establecemos los valores iniciales

In [22]:
servidores_activos = 1
llegadas = 10 #por hora
capacidad_servicio = 12 #por hora y por servidor
hora_inicio = datetime.datetime.strptime('09:00', '%H:%M')
hora_final = datetime.datetime.strptime('14:00', '%H:%M')

2.creacion de clientes

In [23]:
df = pd.DataFrame()

#generacion de tiempos de llegadas
tiempo_entre_llegadas = []

horas = []
aux_time=hora_inicio
while(aux_time < hora_final):
    aux_llegada = (-np.log(1-np.random.uniform(0,1))/llegadas)*60
    tiempo_entre_llegadas.append(aux_llegada)
    aux_time = aux_time + datetime.timedelta(minutes=aux_llegada)
    horas.append(aux_time.strftime("%H:%M:%S"))
momento_de_llegada = acumular_array(tiempo_entre_llegadas)

df.insert(0 , 'hora de llegada' , horas)
df.insert(1 , 'tiempo entre llegadas', tiempo_entre_llegadas)
df.insert(2 , 'momento de llegada' , momento_de_llegada)
df

   hora de llegada  tiempo entre llegadas  momento de llegada
0         09:04:14               4.242672            4.242672
1         09:06:19               2.090496            6.333167
2         09:16:32              10.209013           16.542180
3         09:17:39               1.123345           17.665525
4         09:27:24               9.739671           27.405195
5         09:36:36               9.201099           36.606294
6         09:38:06               1.504584           38.110878
7         09:45:52               7.764241           45.875119
8         09:57:07              11.255617           57.130736
9         10:02:55               5.789135           62.919871
10        10:13:17              10.365956           73.285828
11        10:23:37              10.337393           83.623220
12        10:27:59               4.372043           87.995263
13        10:32:21               4.361659           92.356923
14        10:42:20               9.992794          102.349717
15        10:46:19               3.978908          106.328625
16        10:56:45              10.437638          116.766263
17        11:01:41               4.928165          121.694428
18        11:01:56               0.250520          121.944948
19        11:02:52               0.937350          122.882298
20        11:05:24               2.520102          125.402400
21        11:11:18               5.907608          131.310008
22        11:24:33              13.246412          144.556420
23        11:33:38               9.077278          153.633698
24        11:45:04              11.446667          165.080365
25        11:49:17               4.217373          169.297738
26        11:57:16               7.975403          177.273141
27        11:57:25               0.144547          177.417688
28        12:12:36              15.189595          192.607283
29        12:23:14              10.636542          203.243825
30        12:26:22               3.136836          206.380661
31        12:32:07               5.752542          212.133203
32        12:42:58              10.834887          222.968090
33        12:48:04               5.104199          228.072289
34        13:12:58              24.897331          252.969620
35        13:15:07               2.158610          255.128230
36        13:15:35               0.457726          255.585956
37        13:21:00               5.419964          261.005920
38        13:21:01               0.020339          261.026259
39        13:25:56               4.912764          265.939023
40        13:26:26               0.502065          266.441088
41        13:27:12               0.763230          267.204318
42        13:31:49               4.618069          271.822387
43        13:34:05               2.264774          274.087161
44        13:36:11               2.108801          276.195963
45        13:38:25               2.235751          278.431714
46        13:44:13               5.795720          284.227434
47        13:52:16               8.051956          292.279390
48        13:57:39               5.384220          297.663610
49        14:08:31              10.866065          308.529675

3.creacion de servidores y atencion

In [24]:
servidores = [0.0 for _ in range(servidores_activos)]
num_clientes = len(momento_de_llegada)

tiempo_inicio_servicio = np.zeros(num_clientes)
tiempo_terminacion_servicio = np.zeros(num_clientes)
tiempo_de_servicio = [(-np.log(1-np.random.uniform(0,1))/capacidad_servicio)*60 for _ in range(num_clientes)]
cliente_servidor = np.zeros(num_clientes)

for i in range(num_clientes):
        mejor_servidor = servidores.index(min(servidores))
        tiempo_inicio_servicio[i] = max(momento_de_llegada[i], servidores[mejor_servidor])
        tiempo_terminacion_servicio[i] = tiempo_inicio_servicio[i] + tiempo_de_servicio[i]
        servidores[mejor_servidor] = tiempo_terminacion_servicio[i]
        cliente_servidor[i] = mejor_servidor+1 

tiempo_espera = [ inicio_servicio - llegada for inicio_servicio,llegada in zip(tiempo_inicio_servicio,momento_de_llegada)]

df.insert(3 , 'tiempo de espera', tiempo_espera)
df.insert(4 , 'tiempo de inicio de servicio', tiempo_inicio_servicio)
df.insert(5 , 'tiempo de servicio', tiempo_de_servicio)
df.insert(6 , 'tiempo de terminacion de servicio', tiempo_terminacion_servicio)
df.insert(7 , 'servidor', cliente_servidor)
df.to_csv('cola.csv',index=False)
df

,hora de llegada,tiempo entre llegadas,momento de llegada,tiempo de espera,tiempo de inicio de servicio,tiempo de servicio,tiempo de terminacion de servicio,servidor
0,09:04:14,4.242672,4.242672,0.000000,4.242672,0.837482,5.080154,1.0
1,09:06:19,2.090496,6.333167,0.000000,6.333167,5.910253,12.243421,1.0
2,09:16:32,10.209013,16.542180,0.000000,16.542180,12.654393,29.196573,1.0
3,09:17:39,1.123345,17.665525,11.531048,29.196573,3.954644,33.151217,1.0
4,09:27:24,9.739671,27.405195,5.746021,33.151217,12.625892,45.777108,1.0
5,09:36:36,9.201099,36.606294,9.170814,45.777108,2.124284,47.901393,1.0
6,09:38:06,1.504584,38.110878,9.790515,47.901393,1.031883,48.933276,1.0
7,09:45:52,7.764241,45.875119,3.058156,48.933276,3.640352,52.573628,1.0
8,09:57:07,11.255617,57.130736,0.000000,57.130736,4.079390,61.210126,1.0
9,10:02:55,5.789135,62.919871,0.000000,62.919871,5.116764,68.036635,1.0
10,10:13:17,10.365956,73.285828,0.000000,73.285828,5.363808,78.649636,1.0
11,10:23:37,10.337393,83.623220,0.000000,83.623220,1.294770,84.917990,1.0
12,10:27:59,4.372043,87.995263,0.000000,87.995263,3.773331,91.768594,1.0
13,10:32:21,4.361659,92.356923,0.000000,92.356923,4.265768,96.622691,1.0
14,10:42:20,9.992794,102.349717,0.000000,102.349717,3.132600,105.482317,1.0
15,10:46:19,3.978908,106.328625,0.000000,106.328625,9.391862,115.720487,1.0
16,10:56:45,10.437638,116.766263,0.000000,116.766263,9.305411,126.071674,1.0
17,11:01:41,4.928165,121.694428,4.377246,126.071674,1.603431,127.675105,1.0
18,11:01:56,0.250520,121.944948,5.730157,127.675105,0.773238,128.448343,1.0
19,11:02:52,0.937350,122.882298,5.566045,128.448343,11.271029,139.719373,1.0
20,11:05:24,2.520102,125.402400,14.316972,139.719373,8.029894,147.749267,1.0
21,11:11:18,5.907608,131.310008,16.439258,147.749267,10.296696,158.045962,1.0
22,11:24:33,13.246412,144.556420,13.489542,158.045962,2.162769,160.208732,1.0
23,11:33:38,9.077278,153.633698,6.575034,160.208732,1.106509,161.315241,1.0
24,11:45:04,11.446667,165.080365,0.000000,165.080365,7.354968,172.435333,1.0
25,11:49:17,4.217373,169.297738,3.137595,172.435333,0.422329,172.857662,1.0
26,11:57:16,7.975403,177.273141,0.000000,177.273141,3.186651,180.459792,1.0
27,11:57:25,0.144547,177.417688,3.042105,180.459792,0.791839,181.251632,1.0
28,12:12:36,15.189595,192.607283,0.000000,192.607283,3.465125,196.072408,1.0
29,12:23:14,10.636542,203.243825,0.000000,203.243825,5.001505,208.245330,1.0
30,12:26:22,3.136836,206.380661,1.864669,208.245330,6.993617,215.238947,1.0
31,12:32:07,5.752542,212.133203,3.105744,215.238947,7.212370,222.451316,1.0
32,12:42:58,10.834887,222.968090,0.000000,222.968090,0.000083,222.968173,1.0
33,12:48:04,5.104199,228.072289,0.000000,228.072289,0.312595,228.384885,1.0
34,13:12:58,24.897331,252.969620,0.000000,252.969620,3.049758,256.019378,1.0
35,13:15:07,2.158610,255.128230,0.891148,256.019378,9.659537,265.678915,1.0
36,13:15:35,0.457726,255.585956,10.092959,265.678915,1.715516,267.394431,1.0
37,13:21:00,5.419964,261.005920,6.388511,267.394431,1.387292,268.781724,1.0
38,13:21:01,0.020339,261.026259,7.755464,268.781724,3.683306,272.465030,1.0
39,13:25:56,4.912764,265.939023,6.526007,272.465030,5.160629,277.625659,1.0
40,13:26:26,0.502065,266.441088,11.184571,277.625659,0.648956,278.274616,1.0
41,13:27:12,0.763230,267.204318,11.070298,278.274616,3.849697,282.124313,1.0
42,13:31:49,4.618069,271.822387,10.301926,282.124313,3.839989,285.964302,1.0
43,13:34:05,2.264774,274.087161,11.877140,285.964302,0.205317,286.169618,1.0
44,13:36:11,2.108801,276.195963,9.973656,286.169618,2.714387,288.884006,1.0
45,13:38:25,2.235751,278.431714,10.452292,288.884006,3.309881,292.193887,1.0
46,13:44:13,5.795720,284.227434,7.966453,292.193887,1.155695,293.349582,1.0
47,13:52:16,8.051956,292.279390,1.070192,293.349582,11.720243,305.069825,1.0
48,13:57:39,5.384220,297.663610,7.406215,305.069825,19.904948,324.974773,1.0
49,14:08:31,10.866065,308.529675,16.445097,324.974773,3.843034,328.817807,1.0

In [25]:
print(f"promedio de tiempo entre llegadas: {sum(tiempo_entre_llegadas)/len(tiempo_entre_llegadas)}")
print(f"promedio de tiempo de espera: {sum(tiempo_espera)/len(tiempo_espera)}")
print(f"promedio de tiempo de servicio: {sum(tiempo_de_servicio)/len(tiempo_de_servicio)}")

promedio de tiempo entre llegadas: 6.170593508890049
promedio de tiempo de espera: 4.92685704228637
promedio de tiempo de servicio: 4.686714459718395